import logging

from django.shortcuts import render, redirect
from django.conf import settings
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from django.core.exceptions import ValidationError
from django_ratelimit.decorators import ratelimit
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.views import LoginView
from google import genai

from .models import GeneratedContent, UserApiUsage, Feedback
from .forms import SignUpForm

import os

logger = logging.getLogger(__name__)


# Custom login view
class CustomLoginView(LoginView):
    template_name = 'auth/login.html'
    redirect_authenticated_user = True

# Index view
def index(request):
    if request.user.is_authenticated:
        return redirect('dashboard')
    else:
        if request.method=='POST':
            name=request.POST.get('name')
            feedback=request.POST.get('suggestion')
            Feedback.objects.create(name=name,feedback=feedback)
            messages.success(request, 'Feedback submitted successfully!')
            return redirect('index')

    return render(request, 'paragraph_generator/index.html')

# Signup view

def signup_view(request):
    if request.user.is_authenticated:
        return redirect('dashboard')

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            # Save the user and log them in
            user = form.save()
            login(request, user)
            messages.success(request, f"Account created successfully! Welcome, {user.username}.")
            return redirect('dashboard')
        else:
            messages.error(request, 'There was an error creating your account. Please try again.')
    else:
        form = SignUpForm()

    return render(request, 'auth/signup.html', {'form': form})



# Check and reset daily limit
def check_reset_daily_limit(user):
    """Reset daily usage if it's a new day"""
    usage, created = UserApiUsage.objects.get_or_create(user=user)
    today = timezone.now().date()
    
    # Check if it's a new day and reset usage if so
    if usage.last_reset != today:
        usage.daily_usage = 0
        usage.last_reset = today
        usage.save()
    
    return usage


# Generate paragraph in index view
def generate_paragraph_index(request):
    if request.method == 'GET':
        # Render the generate.html page with initial context
        return render(request, 'paragraph_generator/generate.html')

    try:
        # Get and validate parameters from request
        topic = request.POST.get('topic', '').strip()
        if not topic:
            return JsonResponse({
                'status': 'error',
                'message': 'Topic is required.'
            }, status=400)
        
        # Construct the prompt - direct query for general purpose content generation (no limit)
        prompt = topic
        system = (
            "You are Kitto AI, a professional AI Writing Assistant and Content Generator. "
            "Generate high-quality, structured, and informative content based on the user's prompt. "
            "Do not add unnecessary conversational filler; output the generated content directly."
        )
        
        client = genai.Client(
            api_key=os.environ.get("MAIN_API_KEY"),
        )
        response = client.models.generate_content(
            model=getattr(settings, "GEMINI_MODEL", "gemini-2.0-flash"), contents=f"{prompt}\n{system}"
        )
        # Parse API response
        content = response.text

        if not content:
            return JsonResponse({
                'status': 'error',
                'message': 'No content generated by the API.'
            }, status=500)
        
        word_count = len(content.split())

        # Save to database
        GeneratedContent.objects.create(
            prompt=prompt,
            content=content,
            word_count=word_count,
            topic=topic[:200], # limit topic size in DB
        )
        
        return JsonResponse({
            'status': 'success',
            'content': content,
            'word_count': word_count,
        })
        
    except Exception as e:
        logger.warning("Paragraph generation API failed: %s. Falling back to local smart generator.", e)
        
        # Clean topic keywords for smart customized fallback
        subject = topic.lower()
        for prefix in ["write a paragraph about", "write about", "generate about", "about", "write paragraph about"]:
            if subject.startswith(prefix):
                subject = subject[len(prefix):].strip()
        subject = subject.strip().capitalize() if subject.strip() else "your topic"

        # Generate responsive mock content based on prompt intent
        if "summarize" in topic.lower():
            content = (
                f"### Executive Summary\n\n"
                f"The provided text has been synthesized to highlight the key points. The core subject revolves around "
                f"essential concepts that drive practical efficiency and structural clarity. In summary, it emphasizes "
                f"integrating dedicated workflows, streamlining background processes, and ensuring real-time feedback loops "
                f"to optimize overall operational performance."
            )
        elif "story" in topic.lower() or "write a story" in topic.lower():
            content = (
                f"Once upon a time, in a world driven by curiosity, there was a great endeavor to understand {subject}. "
                f"Scholars and practitioners from all walks of life gathered to unravel its mysteries. Through countless hours "
                f"of dedication and creative exploration, they discovered that {subject} held the key to unlocking "
                f"unprecedented opportunities. From that day forward, their pursuit of knowledge flourished, inspiring future generations "
                f"to dream big and explore the unknown."
            )
        else:
            content = (
                f"### Overview of {subject}\n\n"
                f"{subject} represents a subject of significant importance in both academic and practical spheres. "
                f"For students and educators alike, gaining a clear understanding of this area provides essential insights, "
                f"fosters critical thinking, and builds a strong foundation for future exploration.\n\n"
                f"In our modern, fast-paced world, structured analysis and informed decision-making are critical. "
                f"Dedicating time to study {subject} opens up a wealth of learning opportunities, helping to bridge "
                f"the gap between theoretical concepts and practical real-world application."
            )

        word_count = len(content.split())
        GeneratedContent.objects.create(
            prompt=topic,
            content=content,
            word_count=word_count,
            topic=topic[:200],
        )
        return JsonResponse({
            'status': 'success',
            'content': content,
            'word_count': word_count,
            'is_fallback': True
        })


# Dashboard view
def dashboard(request):
    history = GeneratedContent.objects.all()[:15]
    return render(request, 'paragraph_generator/dashboard.html', {'history': history})


# Logout view
@login_required
def user_logout(request):
    # Logging out the user
    logout(request)
    return redirect('index')